version: '3.3'
services:
  pozos-registry:
    image: registry:2.8.3
    container_name: pozos-registry
    restart: always
    ports: 
      - "5050:5000"
    volumes:
      - /opt/docker/registry:/var/lib/registry
      - /reg_pwd
    environment:
      - REGISTRY_STORAGE_DELETE_ENABLED=true
      - REGISTRY_AUTH=passwd
      - "REGISTRY_AUTH_HTPASSWD_REALM=Registry Realm"
      - REGISTRY_AUTH_HTPASSWD_PATH=/reg_pwd/passwd
    command:
      - /bin/sh
      - -c
      - 'apk add --no-cache apache2-utils && htpasswd -Bbn pozos change-me > /reg_pwd/passwd && registry serve /etc/docker/registry/config.yml'
    networks:
      - pozos_registry_network

  front-registry:
    image: joxit/docker-registry-ui:2
    container_name: front-registry
    depends_on:
      - pozos-registry
    ports: 
      - "9090:80"
    environment:
      - NGINX_PROXY_PASS_URL=http://pozos-registry:5050
      - DELETE_IMAGES=true
      - REGISTRY_TITLE=Our_Registry
      - SINGLE_REGISTRY=true
    networks:
      - pozos_registry_network

networks:
  pozos_registry_network:
